### ISSUE TITLE
Corregir Constants.name_in_url

### ISSUE THREAD

**Issue by mgutierrezc** [verduralegorica/meds_primero_t#3]
Los valores que identifiquen su sesión de control y tratamiento deben ser diferentes

`
ValueError: App Meds_primero_t has Constants.name_in_url='experimento_de_medicamentos1', which is already used by another app
`

**Comment by mgutierrezc** [comment]
Asimismo, denle un valor que **no** identifique el tema de su experimento y si estan en el grupo de control o tratamiento, pues es un valor **público**, es decir, que los participantes pueden observar

Todos los valores de ese tipo deben ser **genéricos**. Podrían colocar en su lugar algo como `estd-decis-med`

**Comment by verduralegorica** [comment]
Listo!
